joy_teleop:
  ros__parameters:
    axis_linear:
      x: 1 # LJoy up-down
      z: 2 # LJoy left-right
     
    scale_linear:
      x: 3.0
      z: 0.1
     
    scale_linear_turbo:
      x: 1.0
      z: 1.0
  
    axis_angular:
      zaw: 2 # RJoy left-right
    scale_angular:
      zaw: 1.0
    scale_angular_turbo:
      Zaw: 1.0
    require_enable_button: false
    enable_turbo_button: 10  # R1 shoulder button